#!/usr/bin/env bash
cd ..
git fetch
git pull
git add . 
git commit -m "Updates" 
git push
cp -R ~/Desktop/KalinduDahanayake.github.io/Output/ ~/Desktop/Website\ Deployment
cd  ~/Desktop/Website\ Deployment
git fetch
git pull
git add .
git commit -m "Updates"
git push
cd ~/Desktop/KalinduDahanayake.github.io/Scripts
